import {
  AppraisalIcon,
  SpamShieldIcon,
  WhoisIcon,
  FacebookIcon,
  TwitterIcon,
  LinkedInIcon,
  InstagramIcon,
  TiktokIcon,
  GoogleIcon,
  GoogleMapsIcon,
  WaybackIcon,
  DnsHistoryIcon,
  ExtraToolsIcon,
  SimilarWebIcon,
  TrademarkIcon,
  DomainGeneratorIcon,
} from './components/icons';
import type { Tool } from './types';

export const TOOLS: Tool[] = [
  // Appraisal
  {
    id: 'atom',
    title: 'Atom Domain Appraisal',
    description: 'Get an AI-powered domain valuation from Atom.com.',
    urlTemplate: 'https://www.atom.com/domain-appraisal',
    Icon: AppraisalIcon,
    category: 'Appraisal',
  },
  {
    id: 'dynadot',
    title: 'Dynadot Domain Appraisal',
    description: 'Use Dynadot\'s tool to estimate the value of your domain.',
    urlTemplate: 'https://www.dynadot.com/domain/appraisal',
    Icon: AppraisalIcon,
    category: 'Appraisal',
  },
  {
    id: 'godaddy',
    title: 'GoDaddy Domain Appraisal',
    description: 'Estimate your domain\'s value with GoDaddy\'s data-driven tool.',
    urlTemplate: 'https://www.godaddy.com/domain-value-appraisal/appraisal/?domainToCheck={{DOMAIN}}',
    Icon: AppraisalIcon,
    category: 'Appraisal',
  },
  {
    id: 'humbleworth',
    title: 'HumbleWorth Valuation',
    description: 'Get a quick domain valuation based on various metrics.',
    urlTemplate: 'https://humbleworth.com/valuation/single?domain={{DOMAIN}}',
    Icon: AppraisalIcon,
    category: 'Appraisal',
  },
  {
    id: 'domai',
    title: 'Domai.io Valuation',
    description: 'Free domain name appraisal tool by Domai.io.',
    urlTemplate: 'https://domai.io/domain-valuation/',
    Icon: AppraisalIcon,
    category: 'Appraisal',
  },

  // Spam
  {
    id: 'mxtoolbox',
    title: 'MXToolbox Blacklist Check',
    description: 'Check if your domain is on any email blacklists.',
    urlTemplate: 'https://mxtoolbox.com/SuperTool.aspx?action=blacklist%3a{{DOMAIN}}&run=toolpage',
    Icon: SpamShieldIcon,
    category: 'Spam',
  },
  {
    id: 'talos',
    title: 'Talos Intelligence',
    description: 'Check domain reputation with Cisco Talos Intelligence.',
    urlTemplate: 'https://talosintelligence.com/reputation_center/lookup?search={{DOMAIN}}',
    Icon: SpamShieldIcon,
    category: 'Spam',
  },
  {
    id: 'sucuri',
    title: 'Sucuri SiteCheck',
    description: 'Scan for malware, blacklisting status, and security issues.',
    urlTemplate: 'https://sitecheck.sucuri.net/results/{{DOMAIN}}',
    Icon: SpamShieldIcon,
    category: 'Spam',
  },
  {
    id: 'spamhaus',
    title: 'Spamhaus Check',
    description: 'Check your domain against the Spamhaus blocklists.',
    urlTemplate: 'https://check.spamhaus.org/',
    Icon: SpamShieldIcon,
    category: 'Spam',
  },

  // WHOIS
  {
    id: 'whois',
    title: 'Whois.com Lookup',
    description: 'Find registration and ownership details for a domain.',
    urlTemplate: 'https://www.whois.com/whois/{{DOMAIN}}',
    Icon: WhoisIcon,
    category: 'WHOIS',
  },

  // Social Media
  {
    id: 'facebook',
    title: 'Facebook Page',
    description: 'Check for a Facebook page with the domain name.',
    urlTemplate: 'https://www.facebook.com/{{DOMAIN_NAME}}',
    Icon: FacebookIcon,
    urlType: 'domain_name',
    category: 'Social Media',
  },
  {
    id: 'twitter',
    title: 'Twitter Profile',
    description: 'Check for a Twitter handle with the domain name.',
    urlTemplate: 'https://www.twitter.com/{{DOMAIN_NAME}}',
    Icon: TwitterIcon,
    urlType: 'domain_name',
    category: 'Social Media',
  },
  {
    id: 'linkedin',
    title: 'LinkedIn Company',
    description: 'Check for a LinkedIn company page.',
    urlTemplate: 'https://www.linkedin.com/company/{{DOMAIN_NAME}}',
    Icon: LinkedInIcon,
    urlType: 'domain_name',
    category: 'Social Media',
  },
  {
    id: 'instagram',
    title: 'Instagram Profile',
    description: 'Check for an Instagram profile with the domain name.',
    urlTemplate: 'https://www.instagram.com/{{DOMAIN_NAME}}',
    Icon: InstagramIcon,
    urlType: 'domain_name',
    category: 'Social Media',
  },
  {
    id: 'tiktok',
    title: 'TikTok Profile',
    description: 'Check for a TikTok profile with the domain name.',
    urlTemplate: 'https://www.tiktok.com/@{{DOMAIN_NAME}}',
    Icon: TiktokIcon,
    urlType: 'domain_name',
    category: 'Social Media',
  },

  // Google
  {
    id: 'google-search',
    title: 'Google Search',
    description: 'See how the domain is indexed and appears on Google.',
    urlTemplate: 'https://www.google.com/search?q=site%3A{{DOMAIN}}',
    Icon: GoogleIcon,
    category: 'Google',
  },
  {
    id: 'google-maps',
    title: 'Google Maps Search',
    description: 'Search for the domain name as a location on Google Maps.',
    urlTemplate: 'https://www.google.com/maps/search/{{DOMAIN}}',
    Icon: GoogleMapsIcon,
    category: 'Google',
  },
  {
    id: 'wayback-machine',
    title: 'Wayback Machine',
    description: 'Explore historical snapshots of the domain via Archive.org.',
    urlTemplate: 'https://web.archive.org/web/*/{{DOMAIN}}',
    Icon: WaybackIcon,
    category: 'Google',
  },

  // DNS History
  {
    id: 'complete-dns',
    title: 'Complete DNS History',
    description: 'Check the historical DNS records for a domain.',
    urlTemplate: 'https://completedns.com/dns-history/{{DOMAIN}}',
    Icon: DnsHistoryIcon,
    category: 'DNS History',
  },
  {
    id: 'hosterstats',
    title: 'HosterStats Historical DNS',
    description: 'View historical DNS and hosting provider information.',
    urlTemplate: 'https://www.hosterstats.com/historicaldns.php?domain={{DOMAIN}}',
    Icon: DnsHistoryIcon,
    category: 'DNS History',
  },

  // Extra Tools
  {
    id: 'dotdb',
    title: 'DotDB',
    description: 'Discover domain statistics and related domains.',
    urlTemplate: 'https://dotdb.com/search?q={{DOMAIN}}',
    Icon: ExtraToolsIcon,
    category: 'Extra Tools',
  },
  {
    id: 'similarweb',
    title: 'SimilarWeb',
    description: 'Analyze website traffic and performance metrics.',
    urlTemplate: 'https://www.similarweb.com/website/{{DOMAIN}}/',
    Icon: SimilarWebIcon,
    category: 'Extra Tools',
  },
  {
    id: 'namechk',
    title: 'Namechk',
    description: 'Check username availability across social networks.',
    urlTemplate: 'https://namechk.com/?q={{DOMAIN_NAME}}',
    Icon: ExtraToolsIcon,
    urlType: 'domain_name',
    category: 'Extra Tools',
  },
  {
    id: 'viewdns',
    title: 'ViewDNS DNS Report',
    description: 'Get a comprehensive DNS report from ViewDNS.info.',
    urlTemplate: 'https://viewdns.info/dnsreport/?domain={{DOMAIN}}',
    Icon: ExtraToolsIcon,
    category: 'Extra Tools',
  },

  // Trademark
  {
    id: 'trademarkia',
    title: 'Trademarkia',
    description: 'Search US trademarks.',
    urlTemplate: 'https://www.trademarkia.com/search/trademarks?query={{DOMAIN_NAME}}&reset_page=true&country=us',
    Icon: TrademarkIcon,
    urlType: 'domain_name',
    category: 'Trademark',
  },
  {
    id: 'wipo',
    title: 'WIPO',
    description: 'Global trademark search.',
    urlTemplate: 'https://www.wipo.int/search/en/results?q={{DOMAIN_NAME}}',
    Icon: TrademarkIcon,
    urlType: 'domain_name',
    category: 'Trademark',
  },
  {
    id: 'freetrademarks',
    title: 'FreeTrademarks.net',
    description: 'Free trademark lookup.',
    urlTemplate: 'https://www.freetrademarks.net/search/{{DOMAIN_NAME}}',
    Icon: TrademarkIcon,
    urlType: 'domain_name',
    category: 'Trademark',
  },
  {
    id: 'tmview',
    title: 'TMView',
    description: 'European and international trademarks.',
    urlTemplate: 'https://www.tmdn.org/tmview/#/tmview/welcome?text={{DOMAIN_NAME}}',
    Icon: TrademarkIcon,
    urlType: 'domain_name',
    category: 'Trademark',
  },

  // Domain Generator
  {
    id: 'easynamegenerator',
    title: 'Easy Name Generator',
    description: 'Generate creative domain names.',
    urlTemplate: 'https://easynamegenerator.com/',
    Icon: DomainGeneratorIcon,
    category: 'Domain Generator',
  },
  {
    id: 'geodomaintools',
    title: 'GeoDomainTools',
    description: 'Domain generation with geo-focus.',
    urlTemplate: 'https://geodomaintools.com/',
    Icon: DomainGeneratorIcon,
    category: 'Domain Generator',
  },
  {
    id: 'wordoid',
    title: 'Wordoid',
    description: 'Creative word-based domain generator.',
    urlTemplate: 'https://wordoid.com/',
    Icon: DomainGeneratorIcon,
    category: 'Domain Generator',
  },
];

export const CATEGORIES = ['All', 'Favorites', 'Appraisal', 'Spam', 'WHOIS', 'Social Media', 'Google', 'DNS History', 'Extra Tools', 'Trademark', 'Domain Generator'];